//ERROR TYPES
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ADD_ERROR = 'ADD_ERROR'

//AUTH TYPES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';

export const RESEND_VERIFICATION_MAIL_SUCCESS = 'RESEND_VERIFICATION_MAIL_SUCCESS';
export const RESEND_VERIFICATION_MAIL_FAIL = 'RESEND_VERIFICATION_MAIL_FAIL';

export const VERIFY_TOKEN = 'VERIFY_TOKEN';

//INVITATIONS TYPES
export const INVITATIONS_LOADED = 'INVITATIONS_LOADED';
export const INVITATIONS_LOADING = 'INVITATIONS_LOADING';

export const GET_INVITATIONS_SUCCESS = 'GET_INVITATIONS_SUCCESS';
export const GET_INVITATIONS_FAIL = 'GET_INVITATIONS_FAIL';

export const UPDATE_INVITATION_FAIL = 'UPDATE_INVITATION_FAIL';
export const UPDATE_INVITATION_SUCCESS = 'UPDATE_INVITATION_SUCCESS';

export const CREATE_INVITATION_FAIL = 'CREATE_INVITATION_FAIL';
export const CREATE_INVITATION_SUCCESS = 'CREATE_INVITATION_SUCCESS';

export const SET_TYPE = 'SET_TYPE';
export const SET_PAGE = 'SET_PAGE';

//TWOFACTOR TYPES
export const GET_QRCODE_FAIL = 'GET_QRCODE_FAIL';
export const GET_QRCODE_SUCCESS = 'GET_QRCODE_SUCCESS';

export const ACTIVATE_TWOFACTOR_FAIL = 'ACTIVATE_TWOFACTOR_FAIL';
export const ACTIVATE_TWOFACTOR_SUCCESS = 'ACTIVATE_TWOFACTOR_SUCCESS';

export const QR_IS_LOADING = 'QR_IS_LOADING';

//CONVERSATIONS TYPES
export const CONVERSATIONS_LOADING = 'CONVERSATIONS_LOADING';
export const CONVERSATIONS_LOADED = 'CONVERSATIONS_LOADED';

export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAIL = 'GET_CONVERSATIONS_FAIL';

//SOCKET TYPES
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const JOIN_FAIL = 'JOIN_FAIL';

export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_CONNECTED_SUCCESS = 'SOCKET_CONNECTED_SUCCESS';
export const SOCKET_CONNECTED_FAIL = 'SOCKET_CONNECTED_FAIL';

export const SOCKET_DISCONNECT_SUCCESS = 'SOCKET_DISCONNECT_SUCCESS';
export const SOCKET_DISCONNECT_FAIL = 'SOCKET_DISCONNECT_FAIL';

export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const IS_TYPING = 'IS_TYPING';

export const SET_PUBLIC_PRIVATE_KEY_SUCCESSFUL = 'SET_PUBLIC_PRIVATE_KEY_SUCCESSFUL';
export const SET_PUBLIC_PRIVATE_KEY_FAIL = 'SET_PUBLIC_PRIVATE_KEY_FAIL';

export const PUBLIC_KEY_RECEIVED = 'PUBLIC_KEY_RECEIVED';
















